### ISSUE TITLE
Unable to install apex in the system

### ISSUE THREAD

**Issue by shivaprasad1432** [see--/pneumothorax-segmentation#2]
while installing apex with "pip install apex" command these errors are coming 

Collecting apex
  Using cached apex-0.9.10dev.tar.gz (36 kB)
Collecting cryptacular
  Using cached cryptacular-1.5.5.tar.gz (39 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Dell\AppData\Local\Temp\tmpu7mzb5on'
         cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-w52dxt4s\cryptacular
    Complete output (46 lines):
    scons: Reading SConscript files ...
    DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/:
      File "C:\Users\Dell\AppData\Local\Temp\pip-install-w52dxt4s\cryptacular\SConstruct", line 25:
        env = Environment(
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\scons\SCons\Environment.py", line 990:
        apply_tools(self, tools, toolpath)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\scons\SCons\Environment.py", line 102:
        env.Tool(tool)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\scons\SCons\Environment.py", line 1810:
        tool(self)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\enscons\cpyext.py", line 108:
        ext = get_build_ext()
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\enscons\cpyext.py", line 84:
        cmd.run()
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 340:
        self.build_extensions()
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 449:
        self._build_extensions_serial()
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 474:
        self.build_extension(ext)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\enscons\cpyext.py", line 64:
        build_ext.build_extension(self, ext)
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\command\build_ext.py", line 528:
        objects = self.compiler.compile(sources,
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 360:
        self.initialize()
      File "c:\users\dell\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 253:
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\setuptools\msvc.py", line 314:
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-env-burgfd9h\overlay\Lib\site-packages\setuptools\msvc.py", line 268:
        raise distutils.errors.DistutilsPlatformError(
    Traceback (most recent call last):
      File "c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 163, in _get_wheel_metadata_from_wheel
        whl_file = os.path.join(metadata_directory, whl_basename)
      File "c:\users\dell\appdata\local\programs\python\python38\lib\ntpath.py", line 117, in join
        genericpath._check_arg_types('join', path, *paths)
      File "c:\users\dell\appdata\local\programs\python\python38\lib\genericpath.py", line 152, in _check_arg_types
        raise TypeError(f'{funcname}() argument must be str, bytes, or '
    TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Dell\AppData\Local\Temp\tmpu7mzb5on' Check the logs for full command output.

**Comment by see--** [comment]
The error is quite clear (and unrelated to this repo). You can find more help regarding the apex installation [here](https://github.com/NVIDIA/apex).
